// Auto-generated bodyTypeMap — mapa model → typ nadwozia
// Używana do: (1) podpowiedzi w formularzu wyceny warsztatu
//             (2) fallback dopasowania ceny gdy brak precyzyjnej wyceny
export type BodyTypeKey =
  | "hatchback"
  | "sedan_liftback"
  | "kombi"
  | "suv_crossover"
  | "mpv_van"
  | "coupe_cabrio";

export const bodyTypeMap: Record<string, BodyTypeKey | BodyTypeKey[]> = {
  // ─── Alfa Romeo ───────────────────────────────────────────
  "Alfa Romeo|147": "hatchback",
  "Alfa Romeo|156": "sedan_liftback",
  "Alfa Romeo|159": "sedan_liftback",
  "Alfa Romeo|166": "sedan_liftback",
  "Alfa Romeo|8C Competizione": "coupe_cabrio",
  "Alfa Romeo|Brera": "coupe_cabrio",
  "Alfa Romeo|Giulia": "sedan_liftback",
  "Alfa Romeo|Giulietta": "hatchback",
  "Alfa Romeo|Junior": "suv_crossover",
  "Alfa Romeo|MiTo": "hatchback",
  "Alfa Romeo|Spider": "coupe_cabrio",
  "Alfa Romeo|Stelvio": "suv_crossover",
  "Alfa Romeo|Tonale": "suv_crossover",
  "Alfa Romeo|33 Stradale": "coupe_cabrio",
  // ─── Audi ────────────────────────────────────────────────
  "Audi|A1": "hatchback",
  "Audi|A2": "hatchback",
  "Audi|A3": "hatchback",
  "Audi|A3 allstreet": "hatchback",
  "Audi|A4": ["sedan_liftback", "kombi"],
  "Audi|A5": ["coupe_cabrio", "sedan_liftback"],
  "Audi|A5 (2024)": ["sedan_liftback", "kombi"],
  "Audi|A6": ["sedan_liftback", "kombi"],
  "Audi|A6 e-tron": "sedan_liftback",
  "Audi|A7": "sedan_liftback",
  "Audi|A8": "sedan_liftback",
  "Audi|e-tron": "suv_crossover",
  "Audi|e-tron GT": "sedan_liftback",
  "Audi|RS e-tron GT": "sedan_liftback",
  "Audi|Q2": "suv_crossover",
  "Audi|Q3": "suv_crossover",
  "Audi|Q4 e-tron": "suv_crossover",
  "Audi|Q4 Sportback e-tron": "suv_crossover",
  "Audi|Q5": "suv_crossover",
  "Audi|Q6 e-tron": "suv_crossover",
  "Audi|Q6 e-tron Sportback": "suv_crossover",
  "Audi|Q7": "suv_crossover",
  "Audi|Q8": "suv_crossover",
  "Audi|Q8 e-tron": "suv_crossover",
  "Audi|Q8 e-tron Sportback": "suv_crossover",
  "Audi|R8": "coupe_cabrio",
  "Audi|RS3": "hatchback",
  "Audi|RS4": ["sedan_liftback", "kombi"],
  "Audi|RS5": ["coupe_cabrio", "sedan_liftback"],
  "Audi|RS6": ["sedan_liftback", "kombi"],
  "Audi|RS7": "sedan_liftback",
  "Audi|S3": "hatchback",
  "Audi|S4": ["sedan_liftback", "kombi"],
  "Audi|S5": ["coupe_cabrio", "sedan_liftback"],
  "Audi|S5 (2024)": "sedan_liftback",
  "Audi|S6": "sedan_liftback",
  "Audi|S8": "sedan_liftback",
  "Audi|SQ5": "suv_crossover",
  "Audi|SQ7": "suv_crossover",
  "Audi|SQ8": "suv_crossover",
  "Audi|TT": "coupe_cabrio",
  // ─── BMW ─────────────────────────────────────────────────
  "BMW|128ti": "hatchback",
  "BMW|i3": "hatchback",
  "BMW|i4": "sedan_liftback",
  "BMW|i5": "sedan_liftback",
  "BMW|i7": "sedan_liftback",
  "BMW|iX": "suv_crossover",
  "BMW|iX1": "suv_crossover",
  "BMW|iX2": "suv_crossover",
  "BMW|iX2 M35i": "suv_crossover",
  "BMW|M2": "coupe_cabrio",
  "BMW|M2 CS": "coupe_cabrio",
  "BMW|M3": ["sedan_liftback", "kombi"],
  "BMW|M4": "coupe_cabrio",
  "BMW|M5": ["sedan_liftback", "kombi"],
  "BMW|M5 Touring": "kombi",
  "BMW|M8": "coupe_cabrio",
  "BMW|Seria 1": "hatchback",
  "BMW|Seria 2": ["coupe_cabrio", "hatchback"],
  "BMW|Seria 2 Active Tourer": "mpv_van",
  "BMW|Seria 2 Gran Coupe": "sedan_liftback",
  "BMW|Seria 3": ["sedan_liftback", "kombi"],
  "BMW|Seria 4": ["coupe_cabrio", "sedan_liftback"],
  "BMW|Seria 5": ["sedan_liftback", "kombi"],
  "BMW|Seria 6": ["coupe_cabrio", "sedan_liftback"],
  "BMW|Seria 7": "sedan_liftback",
  "BMW|Seria 8": "coupe_cabrio",
  "BMW|X1": "suv_crossover",
  "BMW|X2": "suv_crossover",
  "BMW|X3": "suv_crossover",
  "BMW|X4": "suv_crossover",
  "BMW|X5": "suv_crossover",
  "BMW|X6": "suv_crossover",
  "BMW|X7": "suv_crossover",
  "BMW|XM": "suv_crossover",
  "BMW|XM Label": "suv_crossover",
  "BMW|Z3": "coupe_cabrio",
  "BMW|Z4": "coupe_cabrio",
  // ─── Chevrolet ───────────────────────────────────────────
  "Chevrolet|Blazer": "suv_crossover",
  "Chevrolet|Blazer EV": "suv_crossover",
  "Chevrolet|Bolt": "hatchback",
  "Chevrolet|Bolt EUV": "suv_crossover",
  "Chevrolet|Camaro": "coupe_cabrio",
  "Chevrolet|Captiva": "suv_crossover",
  "Chevrolet|Colorado": "suv_crossover",
  "Chevrolet|Corvette": "coupe_cabrio",
  "Chevrolet|Equinox": "suv_crossover",
  "Chevrolet|Equinox EV": "suv_crossover",
  "Chevrolet|Malibu": "sedan_liftback",
  "Chevrolet|Silverado": "suv_crossover",
  "Chevrolet|Silverado EV": "suv_crossover",
  "Chevrolet|Sonic": "hatchback",
  "Chevrolet|Spark": "hatchback",
  "Chevrolet|Suburban": "suv_crossover",
  "Chevrolet|Tahoe": "suv_crossover",
  "Chevrolet|Tracker": "suv_crossover",
  "Chevrolet|Trailblazer": "suv_crossover",
  "Chevrolet|Traverse": "suv_crossover",
  "Chevrolet|Trax": "suv_crossover",
  // ─── Chrysler ────────────────────────────────────────────
  "Chrysler|200": "sedan_liftback",
  "Chrysler|300": "sedan_liftback",
  "Chrysler|Crossfire": "coupe_cabrio",
  "Chrysler|Pacifica": "mpv_van",
  "Chrysler|PT Cruiser": "hatchback",
  "Chrysler|Sebring": "sedan_liftback",
  "Chrysler|Voyager": "mpv_van",
  // ─── Citroen ─────────────────────────────────────────────
  "Citroen|Ami": "hatchback",
  "Citroen|Berlingo": "mpv_van",
  "Citroen|Berlingo Electric": "mpv_van",
  "Citroen|C-Elysee": "sedan_liftback",
  "Citroen|C1": "hatchback",
  "Citroen|C2": "hatchback",
  "Citroen|C3": "hatchback",
  "Citroen|C3 (2024)": "hatchback",
  "Citroen|C3 Aircross": "suv_crossover",
  "Citroen|C4": "hatchback",
  "Citroen|C4 (2024 facelift)": "hatchback",
  "Citroen|C4 Cactus": "suv_crossover",
  "Citroen|C4 Picasso": "mpv_van",
  "Citroen|C4 X": "sedan_liftback",
  "Citroen|C5": ["sedan_liftback", "kombi"],
  "Citroen|C5 Aircross": "suv_crossover",
  "Citroen|C5 X": "sedan_liftback",
  "Citroen|ë-C3": "hatchback",
  "Citroen|Xsara Picasso": "mpv_van",
  // ─── Cupra ───────────────────────────────────────────────
  "Cupra|Ateca": "suv_crossover",
  "Cupra|Born": "hatchback",
  "Cupra|Born VZ": "hatchback",
  "Cupra|Formentor": "suv_crossover",
  "Cupra|Leon": "hatchback",
  "Cupra|Leon VZ": "hatchback",
  "Cupra|Tavascan": "suv_crossover",
  "Cupra|Terramar": "suv_crossover",
  "Cupra|Terramar PHEV": "suv_crossover",
  // ─── Dacia ───────────────────────────────────────────────
  "Dacia|Bigster": "suv_crossover",
  "Dacia|Bigster (2025)": "suv_crossover",
  "Dacia|Dokker": "mpv_van",
  "Dacia|Duster": "suv_crossover",
  "Dacia|Duster 4x4 (2024)": "suv_crossover",
  "Dacia|Jogger": "kombi",
  "Dacia|Lodgy": "mpv_van",
  "Dacia|Logan": "sedan_liftback",
  "Dacia|Logan MCV": "kombi",
  "Dacia|Sandero": "hatchback",
  "Dacia|Spring": "hatchback",
  // ─── Dodge ───────────────────────────────────────────────
  "Dodge|Challenger": "coupe_cabrio",
  "Dodge|Charger": "sedan_liftback",
  "Dodge|Charger Daytona EV": "sedan_liftback",
  "Dodge|Dart": "sedan_liftback",
  "Dodge|Durango": "suv_crossover",
  "Dodge|Hornet": "suv_crossover",
  "Dodge|Journey": "suv_crossover",
  "Dodge|Viper": "coupe_cabrio",
  // ─── DS Automobiles ──────────────────────────────────────
  "DS Automobiles|DS 3": "hatchback",
  "DS Automobiles|DS 4": "hatchback",
  "DS Automobiles|DS 5": "hatchback",
  "DS Automobiles|DS 7": "suv_crossover",
  "DS Automobiles|DS 8": "sedan_liftback",
  "DS Automobiles|DS 9": "sedan_liftback",
  // ─── Fiat ────────────────────────────────────────────────
  "Fiat|500": "hatchback",
  "Fiat|500e": "hatchback",
  "Fiat|500X": "suv_crossover",
  "Fiat|600e": "suv_crossover",
  "Fiat|Brava": "hatchback",
  "Fiat|Bravo": "hatchback",
  "Fiat|Croma": "hatchback",
  "Fiat|Doblo": "mpv_van",
  "Fiat|Freemont": "suv_crossover",
  "Fiat|Grande Punto": "hatchback",
  "Fiat|Grande Panda": "hatchback",
  "Fiat|Multipla": "mpv_van",
  "Fiat|Panda": "hatchback",
  "Fiat|Punto": "hatchback",
  "Fiat|Seicento": "hatchback",
  "Fiat|Stilo": "hatchback",
  "Fiat|Tipo": "sedan_liftback",
  "Fiat|Tipo Cross": "suv_crossover",
  // ─── Ford ────────────────────────────────────────────────
  "Ford|Bronco": "suv_crossover",
  "Ford|C-Max": "mpv_van",
  "Ford|Capri": "suv_crossover",
  "Ford|EcoSport": "suv_crossover",
  "Ford|Edge": "suv_crossover",
  "Ford|Explorer": "suv_crossover",
  "Ford|Explorer EV": "suv_crossover",
  "Ford|Explorer (EU 2024)": "suv_crossover",
  "Ford|Fiesta": "hatchback",
  "Ford|Focus": ["hatchback", "kombi"],
  "Ford|Fusion": "sedan_liftback",
  "Ford|Galaxy": "mpv_van",
  "Ford|Ka": "hatchback",
  "Ford|Kuga": "suv_crossover",
  "Ford|Kuga PHEV": "suv_crossover",
  "Ford|Mondeo": ["sedan_liftback", "kombi"],
  "Ford|Mustang": "coupe_cabrio",
  "Ford|Mustang Mach-E": "suv_crossover",
  "Ford|Puma": "suv_crossover",
  "Ford|Puma ST": "suv_crossover",
  "Ford|Ranger": "suv_crossover",
  "Ford|S-Max": "mpv_van",
  // ─── Honda ───────────────────────────────────────────────
  "Honda|Accord": "sedan_liftback",
  "Honda|CR-V": ["suv_crossover", "kombi"],
  "Honda|CR-V e:PHEV": "suv_crossover",
  "Honda|CR-Z": "coupe_cabrio",
  "Honda|Civic": ["hatchback", "sedan_liftback"],
  "Honda|e": "hatchback",
  "Honda|e:Ny1": "suv_crossover",
  "Honda|HR-V": "suv_crossover",
  "Honda|Insight": "sedan_liftback",
  "Honda|Jazz": "hatchback",
  "Honda|Jazz e:HEV": "hatchback",
  "Honda|NSX": "coupe_cabrio",
  "Honda|Prelude": "coupe_cabrio",
  "Honda|Prologue": "suv_crossover",
  "Honda|S2000": "coupe_cabrio",
  "Honda|ZR-V": "suv_crossover",
  // ─── Hyundai ─────────────────────────────────────────────
  "Hyundai|Accent": "sedan_liftback",
  "Hyundai|Bayon": "suv_crossover",
  "Hyundai|Casper": "hatchback",
  "Hyundai|Elantra": "sedan_liftback",
  "Hyundai|Grandeur": "sedan_liftback",
  "Hyundai|INSTER": "hatchback",
  "Hyundai|Ioniq": "hatchback",
  "Hyundai|Ioniq 5": "suv_crossover",
  "Hyundai|Ioniq 5 N": "suv_crossover",
  "Hyundai|Ioniq 6": "sedan_liftback",
  "Hyundai|Ioniq 6 N": "sedan_liftback",
  "Hyundai|Ioniq 9": "suv_crossover",
  "Hyundai|Kona": "suv_crossover",
  "Hyundai|Kona Electric": "suv_crossover",
  "Hyundai|NEXO": "suv_crossover",
  "Hyundai|Palisade": "suv_crossover",
  "Hyundai|Santa Cruz": "suv_crossover",
  "Hyundai|Santa Fe": "suv_crossover",
  "Hyundai|Sonata": "sedan_liftback",
  "Hyundai|Tucson": "suv_crossover",
  "Hyundai|Tucson PHEV": "suv_crossover",
  "Hyundai|i10": "hatchback",
  "Hyundai|i20": "hatchback",
  "Hyundai|i30": "hatchback",
  "Hyundai|i40": "sedan_liftback",
  "Hyundai|ix35": "suv_crossover",
  // ─── Jaguar ──────────────────────────────────────────────
  "Jaguar|E-Pace": "suv_crossover",
  "Jaguar|F-Pace": "suv_crossover",
  "Jaguar|F-Type": "coupe_cabrio",
  "Jaguar|I-Pace": "suv_crossover",
  "Jaguar|S-Type": "sedan_liftback",
  "Jaguar|X-Type": "sedan_liftback",
  "Jaguar|XE": "sedan_liftback",
  "Jaguar|XF": "sedan_liftback",
  "Jaguar|XJ": "sedan_liftback",
  "Jaguar|XJ220": "coupe_cabrio",
  "Jaguar|XJR": "sedan_liftback",
  // ─── Jeep ────────────────────────────────────────────────
  "Jeep|Avenger": "suv_crossover",
  "Jeep|Cherokee": "suv_crossover",
  "Jeep|Commander": "suv_crossover",
  "Jeep|Compass": "suv_crossover",
  "Jeep|Gladiator": "suv_crossover",
  "Jeep|Gladiator Farout": "suv_crossover",
  "Jeep|Grand Cherokee": "suv_crossover",
  "Jeep|Grand Cherokee 4xe": "suv_crossover",
  "Jeep|Grand Wagoneer": "suv_crossover",
  "Jeep|Liberty": "suv_crossover",
  "Jeep|Patriot": "suv_crossover",
  "Jeep|Recon": "suv_crossover",
  "Jeep|Renegade": "suv_crossover",
  "Jeep|Wrangler": "suv_crossover",
  // ─── Kia ─────────────────────────────────────────────────
  "Kia|Carnival": "mpv_van",
  "Kia|Ceed": ["hatchback", "kombi"],
  "Kia|EV3": "suv_crossover",
  "Kia|EV5": "suv_crossover",
  "Kia|EV6": "suv_crossover",
  "Kia|EV6 GT": "suv_crossover",
  "Kia|EV6 GT-Line": "suv_crossover",
  "Kia|EV9": "suv_crossover",
  "Kia|K5": "sedan_liftback",
  "Kia|K8": "sedan_liftback",
  "Kia|Mohave": "suv_crossover",
  "Kia|Niro": "suv_crossover",
  "Kia|Niro EV": "suv_crossover",
  "Kia|Optima": "sedan_liftback",
  "Kia|Picanto": "hatchback",
  "Kia|ProCeed": "kombi",
  "Kia|Rio": "hatchback",
  "Kia|Seltos": "suv_crossover",
  "Kia|Sorento": "suv_crossover",
  "Kia|Soul": "hatchback",
  "Kia|Sportage": "suv_crossover",
  "Kia|Stinger": "sedan_liftback",
  "Kia|Stonic": "suv_crossover",
  "Kia|Tasman": "suv_crossover",
  "Kia|Telluride": "suv_crossover",
  // ─── Lancia ──────────────────────────────────────────────
  "Lancia|Delta": "hatchback",
  "Lancia|Ypsilon": "hatchback",
  "Lancia|Thesis": "sedan_liftback",
  "Lancia|Kappa": "sedan_liftback",
  // ─── Land Rover ──────────────────────────────────────────
  "Land Rover|Defender": "suv_crossover",
  "Land Rover|Defender 130": "suv_crossover",
  "Land Rover|Defender OCTA": "suv_crossover",
  "Land Rover|Discovery": "suv_crossover",
  "Land Rover|Discovery Sport": "suv_crossover",
  "Land Rover|Freelander": "suv_crossover",
  "Land Rover|Range Rover": "suv_crossover",
  "Land Rover|Range Rover Evoque": "suv_crossover",
  "Land Rover|Range Rover Sport": "suv_crossover",
  "Land Rover|Range Rover Sport SVR": "suv_crossover",
  "Land Rover|Range Rover Velar": "suv_crossover",
  "Land Rover|Range Rover Velar (2024 facelift)": "suv_crossover",
  // ─── Lexus ───────────────────────────────────────────────
  "Lexus|CT": "hatchback",
  "Lexus|ES": "sedan_liftback",
  "Lexus|GS": "sedan_liftback",
  "Lexus|GX": "suv_crossover",
  "Lexus|GX (2024)": "suv_crossover",
  "Lexus|GX 550": "suv_crossover",
  "Lexus|IS": "sedan_liftback",
  "Lexus|LBX": "suv_crossover",
  "Lexus|LC": "coupe_cabrio",
  "Lexus|LS": "sedan_liftback",
  "Lexus|LX": "suv_crossover",
  "Lexus|NX": "suv_crossover",
  "Lexus|RC": "coupe_cabrio",
  "Lexus|RX": "suv_crossover",
  "Lexus|RZ": "suv_crossover",
  "Lexus|TX": "suv_crossover",
  "Lexus|TX 500h": "suv_crossover",
  "Lexus|UX": "suv_crossover",
  // ─── Mazda ───────────────────────────────────────────────
  "Mazda|2": "hatchback",
  "Mazda|3": "hatchback",
  "Mazda|5": "mpv_van",
  "Mazda|6": "sedan_liftback",
  "Mazda|CX-3": "suv_crossover",
  "Mazda|CX-30": "suv_crossover",
  "Mazda|CX-5": "suv_crossover",
  "Mazda|CX-60": "suv_crossover",
  "Mazda|CX-7": "suv_crossover",
  "Mazda|CX-8": "suv_crossover",
  "Mazda|CX-80 PHEV": "suv_crossover",
  "Mazda|CX-9": "suv_crossover",
  "Mazda|EZ-6": "sedan_liftback",
  "Mazda|MX-30": "suv_crossover",
  "Mazda|MX-30 R-EV": "suv_crossover",
  "Mazda|MX-5": "coupe_cabrio",
  "Mazda|RX-8": "coupe_cabrio",
  // ─── Mercedes-Benz ───────────────────────────────────────
  "Mercedes-Benz|AMG GT 4-Door": "sedan_liftback",
  "Mercedes-Benz|C 63 AMG e Performance": "sedan_liftback",
  "Mercedes-Benz|CLA": ["sedan_liftback", "coupe_cabrio"],
  "Mercedes-Benz|CLA Electric": "sedan_liftback",
  "Mercedes-Benz|CLE": "coupe_cabrio",
  "Mercedes-Benz|CLS": "sedan_liftback",
  "Mercedes-Benz|EQA": "suv_crossover",
  "Mercedes-Benz|EQB": "suv_crossover",
  "Mercedes-Benz|EQB 350": "suv_crossover",
  "Mercedes-Benz|EQC": "suv_crossover",
  "Mercedes-Benz|EQE": "sedan_liftback",
  "Mercedes-Benz|EQE SUV": "suv_crossover",
  "Mercedes-Benz|EQG": "suv_crossover",
  "Mercedes-Benz|EQS": "sedan_liftback",
  "Mercedes-Benz|EQS SUV": "suv_crossover",
  "Mercedes-Benz|GLA": "suv_crossover",
  "Mercedes-Benz|GLB": "suv_crossover",
  "Mercedes-Benz|GLC": "suv_crossover",
  "Mercedes-Benz|GLC Coupe": "suv_crossover",
  "Mercedes-Benz|GLE": "suv_crossover",
  "Mercedes-Benz|GLE Coupe": "suv_crossover",
  "Mercedes-Benz|GLS": "suv_crossover",
  "Mercedes-Benz|GLS AMG": "suv_crossover",
  "Mercedes-Benz|Klasa A": "hatchback",
  "Mercedes-Benz|Klasa B": "mpv_van",
  "Mercedes-Benz|Klasa C": ["sedan_liftback", "kombi"],
  "Mercedes-Benz|Klasa E": ["sedan_liftback", "kombi"],
  "Mercedes-Benz|Klasa G": "suv_crossover",
  "Mercedes-Benz|Klasa S": "sedan_liftback",
  "Mercedes-Benz|Viano": "mpv_van",
  "Mercedes-Benz|Vito": "mpv_van",
  // ─── MG ──────────────────────────────────────────────────
  "MG|Cyberster": "coupe_cabrio",
  "MG|EHS PHEV": "suv_crossover",
  "MG|HS": "suv_crossover",
  "MG|MG3": "hatchback",
  "MG|MG4 EV": "hatchback",
  "MG|MG4 Trophy": "hatchback",
  "MG|MG5 EV": "kombi",
  "MG|MG6": "sedan_liftback",
  "MG|MG7": "sedan_liftback",
  "MG|MG9": "suv_crossover",
  "MG|Marvel R": "suv_crossover",
  "MG|One": "suv_crossover",
  "MG|ZS": "suv_crossover",
  "MG|ZS EV": "suv_crossover",
  "MG|ZST": "suv_crossover",
  // ─── Mini ────────────────────────────────────────────────
  "Mini|Aceman": "hatchback",
  "Mini|Cabrio": "coupe_cabrio",
  "Mini|Clubman": "kombi",
  "Mini|Cooper": "hatchback",
  "Mini|Cooper EV": "hatchback",
  "Mini|Cooper JCW (F66)": "hatchback",
  "Mini|Countryman": "suv_crossover",
  "Mini|Countryman EV": "suv_crossover",
  "Mini|Countryman JCW": "suv_crossover",
  "Mini|One": "hatchback",
  "Mini|Paceman": "suv_crossover",
  "Mini|Roadster": "coupe_cabrio",
  // ─── Mitsubishi ──────────────────────────────────────────
  "Mitsubishi|ASX": "suv_crossover",
  "Mitsubishi|Carisma": "sedan_liftback",
  "Mitsubishi|Colt": "hatchback",
  "Mitsubishi|Eclipse Cross": "suv_crossover",
  "Mitsubishi|Eclipse Cross PHEV": "suv_crossover",
  "Mitsubishi|Galant": "sedan_liftback",
  "Mitsubishi|L200": "suv_crossover",
  "Mitsubishi|Lancer": "sedan_liftback",
  "Mitsubishi|Outlander": "suv_crossover",
  "Mitsubishi|Outlander PHEV": "suv_crossover",
  "Mitsubishi|Pajero": "suv_crossover",
  "Mitsubishi|Space Star": "hatchback",
  "Mitsubishi|i-MiEV": "hatchback",
  // ─── Nissan ──────────────────────────────────────────────
  "Nissan|Almera": "sedan_liftback",
  "Nissan|Ariya": "suv_crossover",
  "Nissan|GT-R": "coupe_cabrio",
  "Nissan|Juke": "suv_crossover",
  "Nissan|Juke Hybrid": "suv_crossover",
  "Nissan|Leaf": "hatchback",
  "Nissan|Micra": "hatchback",
  "Nissan|Micra EV (2025)": "hatchback",
  "Nissan|Murano": "suv_crossover",
  "Nissan|Navara": "suv_crossover",
  "Nissan|Note": "hatchback",
  "Nissan|Patrol": "suv_crossover",
  "Nissan|Primera": "sedan_liftback",
  "Nissan|Qashqai": "suv_crossover",
  "Nissan|Qashqai e-Power": "suv_crossover",
  "Nissan|Townstar": "mpv_van",
  "Nissan|X-Trail": "suv_crossover",
  "Nissan|X-Trail e-Power": "suv_crossover",
  // ─── Opel ────────────────────────────────────────────────
  "Opel|Adam": "hatchback",
  "Opel|Astra": ["hatchback", "kombi"],
  "Opel|Astra Electric": ["hatchback", "kombi"],
  "Opel|Astra GSe": "hatchback",
  "Opel|Astra Sports Tourer Electric": "kombi",
  "Opel|Combo": "mpv_van",
  "Opel|Corsa": "hatchback",
  "Opel|Crossland": "suv_crossover",
  "Opel|Frontera": "suv_crossover",
  "Opel|Frontera EV": "suv_crossover",
  "Opel|Grandland": "suv_crossover",
  "Opel|Grandland GSe": "suv_crossover",
  "Opel|Insignia": ["sedan_liftback", "kombi"],
  "Opel|Karl": "hatchback",
  "Opel|Meriva": "mpv_van",
  "Opel|Mokka": "suv_crossover",
  "Opel|Mokka-e": "suv_crossover",
  "Opel|Vectra": "sedan_liftback",
  "Opel|Vivaro": "mpv_van",
  "Opel|Zafira": "mpv_van",
  "Opel|Zafira Electric": "mpv_van",
  // ─── Peugeot ─────────────────────────────────────────────
  "Peugeot|108": "hatchback",
  "Peugeot|206": "hatchback",
  "Peugeot|207": "hatchback",
  "Peugeot|208": "hatchback",
  "Peugeot|2008": "suv_crossover",
  "Peugeot|306": "hatchback",
  "Peugeot|307": "hatchback",
  "Peugeot|308": "hatchback",
  "Peugeot|308 SW PHEV": "kombi",
  "Peugeot|3008": "suv_crossover",
  "Peugeot|406": "sedan_liftback",
  "Peugeot|407": "sedan_liftback",
  "Peugeot|408": "sedan_liftback",
  "Peugeot|408 PHEV": "sedan_liftback",
  "Peugeot|4008": "suv_crossover",
  "Peugeot|5008": "suv_crossover",
  "Peugeot|508": "sedan_liftback",
  "Peugeot|E-208": "hatchback",
  "Peugeot|E-2008": "suv_crossover",
  "Peugeot|E-308": "hatchback",
  "Peugeot|E-3008": "suv_crossover",
  "Peugeot|E-408": "sedan_liftback",
  "Peugeot|E-5008": "suv_crossover",
  "Peugeot|Partner": "mpv_van",
  "Peugeot|Rifter": "mpv_van",
  // ─── Porsche ─────────────────────────────────────────────
  "Porsche|718": "coupe_cabrio",
  "Porsche|911": "coupe_cabrio",
  "Porsche|911 Dakar": "suv_crossover",
  "Porsche|Boxster": "coupe_cabrio",
  "Porsche|Cayenne": "suv_crossover",
  "Porsche|Cayenne Coupe": "suv_crossover",
  "Porsche|Cayenne e-Hybrid (2024)": "suv_crossover",
  "Porsche|Cayman": "coupe_cabrio",
  "Porsche|Macan": "suv_crossover",
  "Porsche|Macan Electric": "suv_crossover",
  "Porsche|Panamera": "sedan_liftback",
  "Porsche|Taycan": "sedan_liftback",
  "Porsche|Taycan Cross Turismo": "kombi",
  "Porsche|Taycan Sport Turismo": "kombi",
  // ─── Renault ─────────────────────────────────────────────
  "Renault|Arkana": "suv_crossover",
  "Renault|Austral": "suv_crossover",
  "Renault|Captur": "suv_crossover",
  "Renault|Clio": "hatchback",
  "Renault|Espace": "mpv_van",
  "Renault|Espace E-Tech": "suv_crossover",
  "Renault|Kadjar": "suv_crossover",
  "Renault|Kangoo": "mpv_van",
  "Renault|Koleos": "suv_crossover",
  "Renault|Laguna": ["sedan_liftback", "kombi"],
  "Renault|Megane": ["hatchback", "kombi"],
  "Renault|Megane E-Tech": "hatchback",
  "Renault|R4 E-Tech": "suv_crossover",
  "Renault|R5 E-Tech": "hatchback",
  "Renault|Rafale": "suv_crossover",
  "Renault|Scenic": "mpv_van",
  "Renault|Scenic E-Tech": "suv_crossover",
  "Renault|Symbioz": "suv_crossover",
  "Renault|Talisman": "sedan_liftback",
  "Renault|Twingo": "hatchback",
  "Renault|Twingo E-Tech": "hatchback",
  "Renault|Zoe": "hatchback",
  // ─── Saab ────────────────────────────────────────────────
  "Saab|9-3": "sedan_liftback",
  "Saab|9-5": "sedan_liftback",
  "Saab|900": "hatchback",
  "Saab|9000": "hatchback",
  // ─── Seat ────────────────────────────────────────────────
  "Seat|Altea": "mpv_van",
  "Seat|Arona": "suv_crossover",
  "Seat|Ateca": "suv_crossover",
  "Seat|Cordoba": "sedan_liftback",
  "Seat|Exeo": "sedan_liftback",
  "Seat|Ibiza": "hatchback",
  "Seat|Leon": "hatchback",
  "Seat|Leon e-Hybrid (2024 facelift)": "hatchback",
  "Seat|Mii": "hatchback",
  "Seat|Tarraco": "suv_crossover",
  "Seat|Toledo": "sedan_liftback",
  // ─── Skoda ───────────────────────────────────────────────
  "Skoda|Citigo": "hatchback",
  "Skoda|Elroq": "suv_crossover",
  "Skoda|Enyaq": "suv_crossover",
  "Skoda|Enyaq Coupe": "suv_crossover",
  "Skoda|Epiq": "suv_crossover",
  "Skoda|Fabia": "hatchback",
  "Skoda|Kamiq": "suv_crossover",
  "Skoda|Karoq": "suv_crossover",
  "Skoda|Kodiaq": "suv_crossover",
  "Skoda|Kodiaq (2024)": "suv_crossover",
  "Skoda|Octavia": ["sedan_liftback", "kombi"],
  "Skoda|Octavia RS": "sedan_liftback",
  "Skoda|Rapid": "sedan_liftback",
  "Skoda|Roomster": "mpv_van",
  "Skoda|Scala": "hatchback",
  "Skoda|Superb": ["sedan_liftback", "kombi"],
  "Skoda|Superb iV": ["sedan_liftback", "kombi"],
  "Skoda|Yeti": "suv_crossover",
  // ─── Smart ───────────────────────────────────────────────
  "Smart|#1": "suv_crossover",
  "Smart|#3": "suv_crossover",
  "Smart|#5": "suv_crossover",
  "Smart|Forfour": "hatchback",
  "Smart|Fortwo": "hatchback",
  "Smart|Roadster": "coupe_cabrio",
  // ─── Subaru ──────────────────────────────────────────────
  "Subaru|BRZ": "coupe_cabrio",
  "Subaru|Crosstrek": "suv_crossover",
  "Subaru|Forester": "suv_crossover",
  "Subaru|Forester e-Boxer": "suv_crossover",
  "Subaru|Impreza": ["sedan_liftback", "hatchback"],
  "Subaru|Impreza (2024)": ["sedan_liftback", "hatchback"],
  "Subaru|Justy": "hatchback",
  "Subaru|Legacy": ["sedan_liftback", "kombi"],
  "Subaru|Levorg": "kombi",
  "Subaru|Outback": "kombi",
  "Subaru|Solterra": "suv_crossover",
  "Subaru|Tribeca": "suv_crossover",
  "Subaru|WRX": ["sedan_liftback", "hatchback"],
  "Subaru|WRX TR": "sedan_liftback",
  "Subaru|XV": "suv_crossover",
  // ─── Suzuki ──────────────────────────────────────────────
  "Suzuki|Across": "suv_crossover",
  "Suzuki|Alto": "hatchback",
  "Suzuki|Baleno": "hatchback",
  "Suzuki|eVitara": "suv_crossover",
  "Suzuki|Fronx": "suv_crossover",
  "Suzuki|Grand Vitara": "suv_crossover",
  "Suzuki|Ignis": "hatchback",
  "Suzuki|Jimny": "suv_crossover",
  "Suzuki|Kizashi": "sedan_liftback",
  "Suzuki|Liana": "kombi",
  "Suzuki|S-Cross": "suv_crossover",
  "Suzuki|S-Cross Hybrid (2024)": "suv_crossover",
  "Suzuki|SX4": "suv_crossover",
  "Suzuki|Swift": "hatchback",
  "Suzuki|Swift (2024 gen)": "hatchback",
  "Suzuki|Vitara": "suv_crossover",
  // ─── Tesla ───────────────────────────────────────────────
  "Tesla|Cybertruck": "suv_crossover",
  "Tesla|Model 3": "sedan_liftback",
  "Tesla|Model 3 Highland (2024)": "sedan_liftback",
  "Tesla|Model S": "sedan_liftback",
  "Tesla|Model X": "suv_crossover",
  "Tesla|Model Y": "suv_crossover",
  "Tesla|Model Y Juniper (2024)": "suv_crossover",
  "Tesla|Roadster": "coupe_cabrio",
  // ─── Toyota ──────────────────────────────────────────────
  "Toyota|4Runner": "suv_crossover",
  "Toyota|Auris": "hatchback",
  "Toyota|Avensis": "sedan_liftback",
  "Toyota|Aygo": "hatchback",
  "Toyota|bZ4X": "suv_crossover",
  "Toyota|bZ3": "sedan_liftback",
  "Toyota|C-HR": "suv_crossover",
  "Toyota|Camry": "sedan_liftback",
  "Toyota|Camry (2024)": "sedan_liftback",
  "Toyota|Celica": "coupe_cabrio",
  "Toyota|Corolla": "sedan_liftback",
  "Toyota|Corolla Cross": "suv_crossover",
  "Toyota|Crown": "sedan_liftback",
  "Toyota|GR Corolla": "hatchback",
  "Toyota|GR Yaris": "hatchback",
  "Toyota|GR86": "coupe_cabrio",
  "Toyota|GT86": "coupe_cabrio",
  "Toyota|Highlander": "suv_crossover",
  "Toyota|Hilux": "suv_crossover",
  "Toyota|Land Cruiser": "suv_crossover",
  "Toyota|Land Cruiser 300": "suv_crossover",
  "Toyota|MR2": "coupe_cabrio",
  "Toyota|Prius": "sedan_liftback",
  "Toyota|Proace": "mpv_van",
  "Toyota|Proace City Verso": "mpv_van",
  "Toyota|RAV4": "suv_crossover",
  "Toyota|Sequoia": "suv_crossover",
  "Toyota|Supra": "coupe_cabrio",
  "Toyota|Tundra": "suv_crossover",
  "Toyota|Venza": "suv_crossover",
  "Toyota|Yaris": "hatchback",
  "Toyota|Yaris Cross": "suv_crossover",
  "Toyota|Yaris GR": "hatchback",
  // ─── Volkswagen ──────────────────────────────────────────
  "Volkswagen|Arteon": ["sedan_liftback", "kombi"],
  "Volkswagen|Beetle": "hatchback",
  "Volkswagen|Bora": "sedan_liftback",
  "Volkswagen|Caddy": "mpv_van",
  "Volkswagen|Golf": ["hatchback", "kombi"],
  "Volkswagen|Golf Alltrack": "kombi",
  "Volkswagen|Golf eHybrid": "hatchback",
  "Volkswagen|Golf Plus": "mpv_van",
  "Volkswagen|Golf R": "hatchback",
  "Volkswagen|ID.2": "hatchback",
  "Volkswagen|ID.3": "hatchback",
  "Volkswagen|ID.4": "suv_crossover",
  "Volkswagen|ID.5": "suv_crossover",
  "Volkswagen|ID.7": "sedan_liftback",
  "Volkswagen|ID.Buzz": "mpv_van",
  "Volkswagen|ID.Buzz LWB": "mpv_van",
  "Volkswagen|ID.GTI": "hatchback",
  "Volkswagen|Jetta": "sedan_liftback",
  "Volkswagen|Passat": ["sedan_liftback", "kombi"],
  "Volkswagen|Passat Alltrack": "kombi",
  "Volkswagen|Polo": "hatchback",
  "Volkswagen|Scirocco": "coupe_cabrio",
  "Volkswagen|Sharan": "mpv_van",
  "Volkswagen|T-Cross": "suv_crossover",
  "Volkswagen|T-Roc": "suv_crossover",
  "Volkswagen|Taigo": "suv_crossover",
  "Volkswagen|Tiguan": "suv_crossover",
  "Volkswagen|Tiguan eHybrid": "suv_crossover",
  "Volkswagen|Touareg": "suv_crossover",
  "Volkswagen|Touareg R": "suv_crossover",
  "Volkswagen|Touran": "mpv_van",
  "Volkswagen|Transporter": "mpv_van",
  "Volkswagen|Up!": "hatchback",
  "Volkswagen|Amarok (2023)": "suv_crossover",
  // ─── Volvo ───────────────────────────────────────────────
  "Volvo|C30": "hatchback",
  "Volvo|EC40": "suv_crossover",
  "Volvo|EX30": "suv_crossover",
  "Volvo|EX30 Twin Motor": "suv_crossover",
  "Volvo|EX40": "suv_crossover",
  "Volvo|EX90": "suv_crossover",
  "Volvo|EX90 Twin Motor": "suv_crossover",
  "Volvo|S40": "sedan_liftback",
  "Volvo|S60": ["sedan_liftback", "kombi"],
  "Volvo|S80": "sedan_liftback",
  "Volvo|S90": ["sedan_liftback", "kombi"],
  "Volvo|V40": "hatchback",
  "Volvo|V50": "kombi",
  "Volvo|V60": ["kombi", "sedan_liftback"],
  "Volvo|V70": "kombi",
  "Volvo|V90": ["kombi", "sedan_liftback"],
  "Volvo|XC40": "suv_crossover",
  "Volvo|XC60": "suv_crossover",
  "Volvo|XC70": "suv_crossover",
  "Volvo|XC90": "suv_crossover",
  // ─── Nowe marki chińskie i inne ───────────────────────────
  "BYD|Atto 3": "suv_crossover",
  "BYD|Dolphin": "hatchback",
  "BYD|Destroyer 05": "sedan_liftback",
  "BYD|Han": "sedan_liftback",
  "BYD|Seal": "sedan_liftback",
  "BYD|Seal U": "suv_crossover",
  "BYD|Seagull": "hatchback",
  "BYD|Sealion 6": "suv_crossover",
  "BYD|Sealion 7": "suv_crossover",
  "BYD|Song Plus": "suv_crossover",
  "BYD|Tang": "suv_crossover",
  "Chery|Tiggo 4 Pro": "suv_crossover",
  "Chery|Tiggo 7 Pro": "suv_crossover",
  "Chery|Tiggo 8 Pro": "suv_crossover",
  "Chery|Arrizo 6 Pro": "sedan_liftback",
  "Genesis|G70": "sedan_liftback",
  "Genesis|G80": "sedan_liftback",
  "Genesis|G90": "sedan_liftback",
  "Genesis|GV60": "suv_crossover",
  "Genesis|GV70": "suv_crossover",
  "Genesis|GV70 Electrified (2024)": "suv_crossover",
  "Genesis|GV80": "suv_crossover",
  "Genesis|GV80 Coupe": "suv_crossover",
  "Genesis|Electrified G80": "sedan_liftback",
  "Haval|Dargo": "suv_crossover",
  "Haval|Dargo X": "suv_crossover",
  "Haval|H2": "suv_crossover",
  "Haval|H6": "suv_crossover",
  "Haval|H6 GT": "suv_crossover",
  "Haval|H9": "suv_crossover",
  "Haval|Jolion": "suv_crossover",
  "Infiniti|Q30": "hatchback",
  "Infiniti|Q50": "sedan_liftback",
  "Infiniti|Q60": "coupe_cabrio",
  "Infiniti|QX30": "suv_crossover",
  "Infiniti|QX50": "suv_crossover",
  "Infiniti|QX55": "suv_crossover",
  "Infiniti|QX55 (2024 facelift)": "suv_crossover",
  "Infiniti|QX60": "suv_crossover",
  "Infiniti|QX80": "suv_crossover",
  "Jaecoo|J7": "suv_crossover",
  "Jaecoo|J8": "suv_crossover",
  "Leapmotor|B10": "suv_crossover",
  "Leapmotor|C01": "sedan_liftback",
  "Leapmotor|C10": "suv_crossover",
  "Leapmotor|T03": "hatchback",
  "Lynk & Co|01": "suv_crossover",
  "Lynk & Co|02": "suv_crossover",
  "Lynk & Co|05": "suv_crossover",
  "Lynk & Co|06": "suv_crossover",
  "Maserati|Ghibli": "sedan_liftback",
  "Maserati|GranTurismo": "coupe_cabrio",
  "Maserati|GranCabrio": "coupe_cabrio",
  "Maserati|Grecale": "suv_crossover",
  "Maserati|Levante": "suv_crossover",
  "Maserati|Quattroporte": "sedan_liftback",
  "Nio|ET5": "sedan_liftback",
  "Nio|ET5 Touring": "kombi",
  "Nio|ET7": "sedan_liftback",
  "Nio|EL6": "suv_crossover",
  "Nio|EL7": "suv_crossover",
  "Nio|ES6": "suv_crossover",
  "Nio|ES8": "suv_crossover",
  "Omoda|5": "suv_crossover",
  "Omoda|5 EV": "suv_crossover",
  "Omoda|7": "suv_crossover",
  "Omoda|E5": "suv_crossover",
  "Polestar|1": "coupe_cabrio",
  "Polestar|2": "sedan_liftback",
  "Polestar|3": "suv_crossover",
  "Polestar|4": "suv_crossover",
  "Polestar|5": "sedan_liftback",
  "Polestar|6": "coupe_cabrio",
  "SsangYong|Korando": "suv_crossover",
  "SsangYong|Musso": "suv_crossover",
  "SsangYong|Rexton": "suv_crossover",
  "SsangYong|Tivoli": "suv_crossover",
  "SsangYong|Torres": "suv_crossover",
  "SsangYong|Torres EVX": "suv_crossover",
  "SsangYong|Torres EVX (2024)": "suv_crossover",
  "Tank|300": "suv_crossover",
  "Tank|400": "suv_crossover",
  "Tank|500": "suv_crossover",
  "Vinfast|VF 6": "suv_crossover",
  "Vinfast|VF 7": "suv_crossover",
  "Vinfast|VF 8": "suv_crossover",
  "Vinfast|VF 9": "suv_crossover",
  "Xpeng|G6": "suv_crossover",
  "Xpeng|G9": "suv_crossover",
  "Xpeng|P7": "sedan_liftback",
  "Xpeng|X9": "mpv_van",
  "Zeekr|001": "kombi",
  "Zeekr|007": "sedan_liftback",
  "Zeekr|009": "mpv_van",
  "Zeekr|X": "suv_crossover",
  // ─── Luksusowe ───────────────────────────────────────────
  "Aston Martin|DB11": "coupe_cabrio",
  "Aston Martin|DBX": "suv_crossover",
  "Aston Martin|DBS": "coupe_cabrio",
  "Aston Martin|Vantage": "coupe_cabrio",
  "Bentley|Bentayga": "suv_crossover",
  "Bentley|Continental GT": "coupe_cabrio",
  "Bentley|Flying Spur": "sedan_liftback",
  "Ferrari|296 GTB": "coupe_cabrio",
  "Ferrari|Portofino": "coupe_cabrio",
  "Ferrari|Purosangue": "suv_crossover",
  "Ferrari|Roma": "coupe_cabrio",
  "Ferrari|SF90": "coupe_cabrio",
  "Lamborghini|Huracan": "coupe_cabrio",
  "Lamborghini|Revuelto": "coupe_cabrio",
  "Lamborghini|Urus": "suv_crossover",
  "Lotus|Eletre": "suv_crossover",
  "Lotus|Emeya": "sedan_liftback",
  "Lotus|Emira": "coupe_cabrio",
  "McLaren|720S": "coupe_cabrio",
  "McLaren|Artura": "coupe_cabrio",
  "McLaren|GT": "coupe_cabrio",
  "McLaren|GTS": "coupe_cabrio",
  "Rolls-Royce|Cullinan": "suv_crossover",
  "Rolls-Royce|Ghost": "sedan_liftback",
  "Rolls-Royce|Phantom": "sedan_liftback",
  "Rolls-Royce|Spectre": "coupe_cabrio",
  // ─── Amerykańskie ────────────────────────────────────────
  "Buick|Enclave": "suv_crossover",
  "Buick|Encore GX": "suv_crossover",
  "Buick|Envision": "suv_crossover",
  "Cadillac|CT4": "sedan_liftback",
  "Cadillac|CT5": "sedan_liftback",
  "Cadillac|Escalade": "suv_crossover",
  "Cadillac|Lyriq": "suv_crossover",
  "Cadillac|XT4": "suv_crossover",
  "Cadillac|XT5": "suv_crossover",
  "Cadillac|XT6": "suv_crossover",
  "GMC|Acadia": "suv_crossover",
  "GMC|Canyon": "suv_crossover",
  "GMC|Sierra": "suv_crossover",
  "GMC|Terrain": "suv_crossover",
  "GMC|Yukon": "suv_crossover",
  "Lincoln|Aviator": "suv_crossover",
  "Lincoln|Corsair": "suv_crossover",
  "Lincoln|Nautilus": "suv_crossover",
  "Lincoln|Navigator": "suv_crossover",
  // ─── Lada ────────────────────────────────────────────────
  "Lada|Granta": "sedan_liftback",
  "Lada|Largus": "kombi",
  "Lada|Niva": "suv_crossover",
  "Lada|Vesta": "sedan_liftback",
};

export function getBodyTypeForModel(
  make: string,
  model: string,
): BodyTypeKey | BodyTypeKey[] | null {
  return bodyTypeMap[`${make}|${model}`] ?? null;
}

export function hasMultipleBodyTypes(make: string, model: string): boolean {
  const val = bodyTypeMap[`${make}|${model}`];
  return Array.isArray(val) && val.length > 1;
}

export const BODY_TYPE_LABELS: Record<BodyTypeKey, string> = {
  hatchback: "Hatchback",
  sedan_liftback: "Sedan / Liftback",
  kombi: "Kombi",
  suv_crossover: "SUV / Crossover",
  mpv_van: "MPV / Van",
  coupe_cabrio: "Coupe / Cabrio",
};
