export const countryOptions = ["Polska"];

export const polishCityOptions = [
  "Andrychów",
  "Bełchatów",
  "Biała Podlaska",
  "Białystok",
  "Bielsko-Biała",
  "Bydgoszcz",
  "Bytom",
  "Chełm",
  "Chorzów",
  "Ciechanów",
  "Cieszyn",
  "Czechowice-Dziedzice",
  "Częstochowa",
  "Dąbrowa Górnicza",
  "Elbląg",
  "Ełk",
  "Gdańsk",
  "Gdynia",
  "Gliwice",
  "Gniezno",
  "Gorzów Wielkopolski",
  "Grudziądz",
  "Inowrocław",
  "Jastrzębie-Zdrój",
  "Jaworzno",
  "Jelenia Góra",
  "Kalisz",
  "Katowice",
  "Kędzierzyn-Koźle",
  "Kielce",
  "Konin",
  "Koszalin",
  "Kraków",
  "Krosno",
  "Kutno",
  "Legionowo",
  "Legnica",
  "Leszno",
  "Lubin",
  "Lublin",
  "Łódź",
  "Łomża",
  "Mielec",
  "Mińsk Mazowiecki",
  "Mysłowice",
  "Nowy Sącz",
  "Nowy Targ",
  "Olsztyn",
  "Opole",
  "Ostrołęka",
  "Ostrów Wielkopolski",
  "Oświęcim",
  "Pabianice",
  "Piła",
  "Piotrków Trybunalski",
  "Płock",
  "Poznań",
  "Pruszków",
  "Przemyśl",
  "Radom",
  "Ruda Śląska",
  "Rybnik",
  "Rzeszów",
  "Siedlce",
  "Skierniewice",
  "Słupsk",
  "Sosnowiec",
  "Stalowa Wola",
  "Starachowice",
  "Stargard",
  "Suwałki",
  "Szczecin",
  "Szczyrk",
  "Świdnica",
  "Tarnowskie Góry",
  "Tarnów",
  "Tomaszów Mazowiecki",
  "Toruń",
  "Tychy",
  "Ustroń",
  "Wadowice",
  "Wałbrzych",
  "Warszawa",
  "Wisła",
  "Włocławek",
  "Wrocław",
  "Zabrze",
  "Zakopane",
  "Zamość",
  "Zgierz",
  "Zielona Góra",
  "Żory",
  "Żyrardów",
  "Żywiec",
];
