export type VehicleTypeKey = "car" | "motorcycle" | "van";

export type VehicleConfig = {
  label: string;
  brands: string[];
  models: Record<string, string[]>;
  fuels: string[];
  services: string[];
  fuelLabel: string;
  serviceLabel: string;
};

export const vehicleTypeOptions: { key: VehicleTypeKey; label: string }[] = [
  { key: "car", label: "Samochód osobowy" },
  { key: "motorcycle", label: "Motocykl" },
  { key: "van", label: "Dostawczy" },
];

export const vehicleData: Record<VehicleTypeKey, VehicleConfig> = {
  car: {
    label: "Samochód osobowy",
    brands: [
      "Abarth",
      "Alfa Romeo",
      "Alpine",
      "Audi",
      "BYD",
      "BMW",
      "Chevrolet",
      "Chrysler",
      "Citroen",
      "Cupra",
      "Dacia",
      "Dodge",
      "DS Automobiles",
      "Fiat",
      "Ford",
      "Genesis",
      "Haval",
      "Honda",
      "Hyundai",
      "Infiniti",
      "Isuzu",
      "Jaguar",
      "Jeep",
      "Kia",
      "Lancia",
      "Land Rover",
      "Lexus",
      "Maserati",
      "Mazda",
      "Mercedes-Benz",
      "MG",
      "Mini",
      "Mitsubishi",
      "Nissan",
      "Opel",
      "Peugeot",
      "Polestar",
      "Porsche",
      "Renault",
      "Saab",
      "Seat",
      "Skoda",
      "Smart",
      "SsangYong",
      "Subaru",
      "Suzuki",
      "Tesla",
      "Toyota",
      "Volkswagen",
      "Volvo",
      "Inna marka",
    ],
    models: {
      Abarth: ["500", "595", "695", "Punto Evo", "124 Spider", "Inny model"],
      Alpine: ["A110", "A290", "Inny model"],
      "Alfa Romeo": [
        "147",
        "156",
        "159",
        "166",
        "33 Stradale",
        "8C Competizione",
        "Brera",
        "Giulia",
        "Giulietta",
        "Junior",
        "MiTo",
        "Spider",
        "Stelvio",
        "Tonale",
      ],
      Audi: [
        "A1",
        "A2",
        "A3",
        "A4",
        "A5",
        "A6",
        "A6 e-tron",
        "A7",
        "A8",
        "Q2",
        "Q3",
        "Q4 e-tron",
        "Q4 Sportback e-tron",
        "Q5",
        "Q6 e-tron",
        "Q6 e-tron Sportback",
        "Q7",
        "Q8",
        "Q8 e-tron",
        "R8",
        "RS3",
        "RS4",
        "RS5",
        "RS6",
        "RS7",
        "RS e-tron GT",
        "S3",
        "S4",
        "S5",
        "S6",
        "S8",
        "SQ5",
        "SQ7",
        "SQ8",
        "TT",
        "e-tron",
        "e-tron GT",
      ],
      BYD: ["Atto 3", "Seal", "Seal U", "Han", "Tang", "Dolphin", "Seagull", "Inny model"],
      BMW: [
        "128ti",
        "M2",
        "M3",
        "M4",
        "M5",
        "M8",
        "Seria 1",
        "Seria 2",
        "Seria 2 Active Tourer",
        "Seria 2 Gran Coupe",
        "Seria 3",
        "Seria 4",
        "Seria 5",
        "Seria 6",
        "Seria 7",
        "Seria 8",
        "X1",
        "X2",
        "X3",
        "X4",
        "X5",
        "X6",
        "X7",
        "XM",
        "Z3",
        "Z4",
        "i3",
        "i4",
        "i5",
        "i7",
        "iX",
        "iX1",
        "iX2",
        "iX3",
      ],
      Chevrolet: [
        "Blazer",
        "Blazer EV",
        "Bolt",
        "Bolt EUV",
        "Camaro",
        "Captiva",
        "Colorado",
        "Corvette",
        "Equinox",
        "Equinox EV",
        "Groove",
        "Malibu",
        "Silverado",
        "Silverado EV",
        "Silverado HD",
        "Sonic",
        "Spark",
        "Suburban",
        "Tahoe",
        "Tracker",
        "Trailblazer",
        "Traverse",
        "Trax",
      ],
      Chrysler: ["200", "300", "Crossfire", "Pacifica", "PT Cruiser", "Sebring", "Voyager"],
      Citroen: [
        "Ami",
        "Berlingo",
        "Berlingo Electric",
        "C-Elysee",
        "C1",
        "C2",
        "C3",
        "C3 Aircross",
        "C4",
        "C4 Cactus",
        "C4 Picasso",
        "C4 X",
        "C5",
        "C5 Aircross",
        "C5 X",
        "Jumper",
        "Xsara Picasso",
        "ë-C3",
      ],
      Cupra: ["Ateca", "Born", "Formentor", "Leon", "Tavascan", "Terramar"],
      Dacia: ["Bigster", "Dokker", "Duster", "Jogger", "Lodgy", "Logan", "Logan MCV", "Sandero", "Spring"],
      Dodge: ["Challenger", "Charger", "Charger Daytona EV", "Dart", "Durango", "Hornet", "Journey", "Viper"],
      "DS Automobiles": ["DS 3", "DS 4", "DS 5", "DS 7", "DS 8", "DS 9"],
      Fiat: [
        "500",
        "500X",
        "500e",
        "600e",
        "Brava",
        "Bravo",
        "Croma",
        "Doblo",
        "Ducato",
        "Freemont",
        "Grande Panda",
        "Grande Punto",
        "Multipla",
        "Panda",
        "Punto",
        "Seicento",
        "Stilo",
        "Tipo",
        "Tipo Cross",
      ],
      Ford: [
        "Bronco",
        "C-Max",
        "EcoSport",
        "Edge",
        "Escort",
        "Explorer",
        "Explorer EV",
        "Fiesta",
        "Focus",
        "Fusion",
        "Galaxy",
        "Ka",
        "Kuga",
        "Kuga PHEV",
        "Mondeo",
        "Mustang",
        "Mustang Mach-E",
        "Puma",
        "Puma ST",
        "Ranger",
        "S-Max",
        "Transit",
      ],
      Genesis: ["G70", "G80", "G90", "GV70", "GV80", "GV60", "Electrified G80", "Inny model"],
      Haval: ["H6", "Jolion", "H2", "H9", "Dargo", "Inny model"],
      Honda: [
        "Accord",
        "CR-V",
        "CR-V e:PHEV",
        "CR-Z",
        "Civic",
        "HR-V",
        "Insight",
        "Jazz",
        "Jazz e:HEV",
        "NSX",
        "Prelude",
        "S2000",
        "ZR-V",
        "e",
        "e:Ny1",
      ],
      Hyundai: [
        "Accent",
        "Bayon",
        "Elantra",
        "Ioniq",
        "Ioniq 5",
        "Ioniq 5 N",
        "Ioniq 6",
        "Ioniq 6 N",
        "Kona",
        "Kona Electric",
        "NEXO",
        "Santa Cruz",
        "Santa Fe",
        "Sonata",
        "Tucson",
        "Tucson PHEV",
        "i10",
        "i20",
        "i30",
        "i40",
        "ix35",
      ],
      Infiniti: ["Q30", "Q50", "Q60", "QX30", "QX50", "QX55", "QX60", "QX80", "Inny model"],
      Isuzu: ["Aska", "D-Max", "MU-X", "Piazza", "Rodeo", "Trooper"],
      Jaguar: ["E-Pace", "F-Pace", "F-Type", "I-Pace", "S-Type", "X-Type", "XE", "XF", "XJ", "XJ220", "XJR"],
      Jeep: [
        "Avenger",
        "Cherokee",
        "Commander",
        "Compass",
        "Gladiator",
        "Grand Cherokee",
        "Grand Cherokee 4xe",
        "Liberty",
        "Patriot",
        "Recon",
        "Renegade",
        "Wrangler",
      ],
      Kia: [
        "Carnival",
        "Ceed",
        "EV3",
        "EV5",
        "EV6",
        "EV6 GT",
        "EV9",
        "K5",
        "Niro",
        "Niro EV",
        "Optima",
        "Picanto",
        "ProCeed",
        "Rio",
        "Seltos",
        "Soul",
        "Sportage",
        "Sorento",
        "Stinger",
        "Stonic",
      ],
      Lancia: ["Beta", "Dedra", "Delta", "Gamma", "Kappa", "Prisma", "Thema", "Thesis", "Ypsilon"],
      "Land Rover": [
        "Defender",
        "Defender 130",
        "Discovery",
        "Discovery Sport",
        "Freelander",
        "Range Rover",
        "Range Rover Evoque",
        "Range Rover Sport",
        "Range Rover Sport SVR",
        "Range Rover Velar",
      ],
      Lexus: ["CT", "ES", "GS", "GX", "GX (2024)", "IS", "LBX", "LC", "LS", "LX", "NX", "RC", "RX", "RZ", "TX", "UX"],
      Maserati: [
        "Ghibli",
        "Levante",
        "Quattroporte",
        "GranTurismo",
        "GranCabrio",
        "Grecale",
        "GC Spider",
        "Inny model",
      ],
      Mazda: ["2", "3", "5", "6", "CX-3", "CX-30", "CX-5", "CX-60", "CX-7", "CX-8", "CX-9", "MX-30", "MX-5", "RX-8"],
      "Mercedes-Benz": [
        "AMG GT 4-Door",
        "CLA",
        "CLA Electric",
        "CLE",
        "CLS",
        "EQA",
        "EQB",
        "EQC",
        "EQE",
        "EQE SUV",
        "EQG",
        "EQS",
        "EQS SUV",
        "GLA",
        "GLB",
        "GLC",
        "GLC Coupe",
        "GLE",
        "GLS",
        "Klasa A",
        "Klasa B",
        "Klasa C",
        "Klasa E",
        "Klasa G",
        "Klasa S",
        "Viano",
        "Vito",
      ],
      MG: ["Cyberster", "HS", "MG3", "MG4 EV", "MG5 EV", "MG6", "MG7", "Marvel R", "One", "ZS", "ZS EV", "ZST"],
      Mini: ["Aceman", "Cabrio", "Clubman", "Cooper", "Cooper EV", "Countryman", "Countryman EV", "One", "Paceman", "Roadster"],
      Mitsubishi: ["ASX", "Carisma", "Colt", "Eclipse Cross", "Galant", "L200", "Lancer", "Outlander", "Pajero", "Space Star", "i-MiEV"],
      Nissan: [
        "Almera",
        "Ariya",
        "GT-R",
        "Juke",
        "Leaf",
        "Micra",
        "Murano",
        "Navara",
        "Note",
        "Patrol",
        "Primera",
        "Qashqai",
        "Qashqai e-Power",
        "Townstar",
        "X-Trail",
        "X-Trail e-Power",
      ],
      Opel: [
        "Adam",
        "Astra",
        "Astra Electric",
        "Astra GSe",
        "Astra Sports Tourer Electric",
        "Combo",
        "Corsa",
        "Crossland",
        "Frontera",
        "Frontera EV",
        "Grandland",
        "Grandland GSe",
        "Insignia",
        "Kadett",
        "Karl",
        "Meriva",
        "Mokka",
        "Mokka-e",
        "Omega",
        "Vectra",
        "Vivaro",
        "Zafira",
      ],
      Peugeot: [
        "1007",
        "106",
        "108",
        "2008",
        "206",
        "207",
        "208",
        "3008",
        "306",
        "307",
        "308",
        "4008",
        "406",
        "407",
        "5008",
        "508",
        "606",
        "607",
        "Boxer",
        "E-2008",
        "E-208",
        "E-3008",
        "E-308",
        "E-408",
        "E-5008",
        "Partner",
        "Rifter",
      ],
      Polestar: ["1", "2", "3", "4", "Inny model"],
      Porsche: [
        "718",
        "911",
        "Boxster",
        "Cayenne",
        "Cayenne Coupe",
        "Cayman",
        "Macan",
        "Macan Electric",
        "Panamera",
        "Taycan",
        "Taycan Cross Turismo",
        "Taycan Sport Turismo",
      ],
      Renault: [
        "Arkana",
        "Austral",
        "Captur",
        "Clio",
        "Espace",
        "Kadjar",
        "Kangoo",
        "Koleos",
        "Laguna",
        "Master",
        "Megane",
        "Megane E-Tech",
        "R4 E-Tech",
        "R5 E-Tech",
        "Rafale",
        "Scenic",
        "Scenic E-Tech",
        "Symbioz",
        "Talisman",
        "Trafic",
        "Twingo",
        "Zoe",
      ],
      Saab: ["9-2X", "9-3", "9-5", "9-7X", "900", "9000"],
      Seat: ["Altea", "Arona", "Ateca", "Cordoba", "Exeo", "Ibiza", "Leon", "Mii", "Tarraco", "Toledo"],
      Skoda: [
        "1000 MB",
        "Citigo",
        "Elroq",
        "Enyaq",
        "Enyaq Coupe",
        "Epiq",
        "Fabia",
        "Favorit",
        "Felicia",
        "Kamiq",
        "Karoq",
        "Kodiaq",
        "Octavia",
        "Rapid",
        "Roomster",
        "Scala",
        "Superb",
        "Yeti",
      ],
      SsangYong: ["Tivoli", "Korando", "Rexton", "Musso", "Torres", "Torres EVX", "Inny model"],
      Smart: ["#1", "#3", "#5", "#6", "Forfour", "Fortwo", "Roadster"],
      Subaru: ["BRZ", "Crosstrek", "Forester", "Impreza", "Justy", "Legacy", "Levorg", "Outback", "Solterra", "Tribeca", "WRX", "WRX TR", "XV"],
      Suzuki: ["Across", "Alto", "Baleno", "Fronx", "Grand Vitara", "Ignis", "Jimny", "Kizashi", "Liana", "S-Cross", "SX4", "Splash", "Swift", "Vitara", "eVitara"],
      Tesla: ["Cybertruck", "Model 3", "Model S", "Model X", "Model Y", "Roadster", "Semi"],
      Toyota: [
        "Aygo",
        "Auris",
        "Avensis",
        "C-HR",
        "Camry",
        "Celica",
        "Corolla",
        "Corolla Cross",
        "Crown",
        "GR86",
        "GT86",
        "Highlander",
        "Hilux",
        "Land Cruiser",
        "Land Cruiser 300",
        "MR2",
        "Prius",
        "Proace",
        "Proace City Verso",
        "RAV4",
        "Supra",
        "Yaris",
        "Yaris Cross",
        "Yaris GR",
        "bZ4X",
      ],
      Volkswagen: [
        "Arteon",
        "Beetle",
        "Bora",
        "Caddy",
        "Golf",
        "Golf Plus",
        "Golf R",
        "Golf eHybrid",
        "ID.2",
        "ID.3",
        "ID.4",
        "ID.5",
        "ID.7",
        "ID.Buzz",
        "Jetta",
        "Passat",
        "Polo",
        "Scirocco",
        "Sharan",
        "T-Cross",
        "T-Roc",
        "Taigo",
        "Tiguan",
        "Tiguan eHybrid",
        "Touran",
        "Touareg",
        "Transporter",
        "Up!",
      ],
      Volvo: ["C30", "EC40", "EX30", "EX40", "EX90", "S40", "S60", "S80", "S90", "V40", "V50", "V60", "V70", "V90", "XC40", "XC60", "XC70", "XC90"],
      "Inna marka": ["Inny model"],
    },
    fuels: ["Benzyna", "Diesel", "LPG", "Hybryda", "Hybryda plug-in", "Elektryczny", "Nie wiem"],
    services: ["Wymiana oleju i filtrów", "Wymiana opon", "Hamulce", "Diagnostyka komputerowa", "Zawieszenie", "Klimatyzacja", "Rozrząd", "Sprzęgło", "Akumulator", "Układ wydechowy", "Geometria kół", "Przegląd przed zakupem", "Naprawa po awarii", "Blacharstwo / lakiernictwo", "Inna usługa"],
    fuelLabel: "Silnik / paliwo",
    serviceLabel: "Czego potrzebujesz?",
  },
  motorcycle: {
    label: "Motocykl",
    brands: ["Honda Moto", "Yamaha", "Kawasaki", "Suzuki Moto", "BMW Motorrad", "KTM", "Ducati", "Harley-Davidson", "Aprilia", "Piaggio", "Vespa", "Triumph", "Moto Guzzi", "Husqvarna", "Indian Motorcycle", "Benelli", "CF Moto", "Kymco", "Sym", "Junak", "Romet", "Zipp", "Keeway", "Malaguti", "Beta", "Sherco", "GasGas", "Royal Enfield", "MV Agusta", "Inna marka"],
    models: {
      "Honda Moto": ["CB125R", "CB500F", "CB650R", "CBR125R", "CBR500R", "CBR600RR", "CBR650R", "CBR1000RR", "Africa Twin", "NC750X", "Rebel 500", "Gold Wing", "Forza 125", "Forza 350", "PCX", "SH125"],
      Yamaha: ["MT-03", "MT-07", "MT-09", "MT-10", "YZF-R125", "YZF-R3", "YZF-R6", "YZF-R1", "Tracer 7", "Tracer 9", "Tenere 700", "XMAX 125", "XMAX 300", "NMAX", "TMAX"],
      Kawasaki: ["Ninja 125", "Ninja 400", "Ninja 650", "Ninja ZX-6R", "Ninja ZX-10R", "Z125", "Z400", "Z650", "Z900", "Z1000", "Versys 650", "Versys 1000", "Vulcan S"],
      "Suzuki Moto": ["GSX-R125", "GSX-R600", "GSX-R750", "GSX-R1000", "GSX-S125", "GSX-S750", "GSX-S1000", "SV650", "V-Strom 650", "V-Strom 1050", "Burgman 125", "Burgman 400", "Hayabusa"],
      "BMW Motorrad": ["G 310 R", "G 310 GS", "F 750 GS", "F 850 GS", "F 900 R", "F 900 XR", "R 1250 GS", "R 1250 RT", "S 1000 R", "S 1000 RR", "S 1000 XR", "K 1600 GT", "C 400 X", "C 400 GT"],
      KTM: ["Duke 125", "Duke 390", "Duke 690", "Duke 790", "Duke 890", "Duke 1290", "RC 125", "RC 390", "Adventure 390", "Adventure 790", "Adventure 890", "Adventure 1290", "EXC", "SX"],
      Ducati: ["Monster", "Panigale V2", "Panigale V4", "Multistrada", "Scrambler", "Diavel", "Hypermotard", "Streetfighter V2", "Streetfighter V4", "Supersport"],
      "Harley-Davidson": ["Sportster", "Iron 883", "Forty-Eight", "Street Bob", "Fat Bob", "Fat Boy", "Road King", "Street Glide", "Road Glide", "Pan America", "Nightster"],
      Aprilia: ["RS 125", "RS 660", "RSV4", "Tuono 125", "Tuono 660", "Tuono V4", "Tuareg 660", "SR GT", "SR 50"],
      Piaggio: ["Liberty", "Medley", "Beverly", "MP3", "Zip", "Typhoon"],
      Vespa: ["Primavera", "Sprint", "GTS", "GTV", "Elettrica"],
      Triumph: ["Trident 660", "Street Triple", "Speed Triple", "Tiger 660", "Tiger 900", "Tiger 1200", "Bonneville", "Bobber", "Rocket 3"],
      "Moto Guzzi": ["V7", "V9", "V85 TT", "California", "Audace"],
      Husqvarna: ["Svartpilen 125", "Svartpilen 401", "Vitpilen 401", "Norden 901", "TE", "FE", "TC", "FC"],
      "Indian Motorcycle": ["Scout", "Chief", "Chieftain", "Challenger", "Roadmaster", "FTR"],
      Benelli: ["BN 125", "Leoncino 500", "TRK 502", "TNT 125", "752S"],
      "CF Moto": ["300NK", "450NK", "650NK", "700CL-X", "800MT", "450SR"],
      Kymco: ["Agility", "Like", "People", "Downtown", "X-Town", "AK 550"],
      Sym: ["Symphony", "Jet", "Fiddle", "Maxsym", "Joymax"],
      Junak: ["901", "902", "905", "M11", "M12", "M16", "RS125", "RX One"],
      Romet: ["Ogar", "Pony", "ZK", "ZXT", "CRS", "ADV"],
      Zipp: ["VZ", "Pro", "Raven", "Shock", "Quantum"],
      Keeway: ["RKS", "RKF", "Superlight", "K-Light", "Fact", "Cityblade"],
      "Royal Enfield": ["Classic 350", "Meteor 350", "Himalayan", "Interceptor 650", "Continental GT", "Super Meteor 650"],
      "Inna marka": ["Inny model"],
    },
    fuels: ["Benzyna", "Elektryczny", "Nie wiem"],
    services: ["Wymiana oleju", "Wymiana filtra oleju", "Wymiana filtra powietrza", "Wymiana opon motocyklowych", "Serwis łańcucha i napędu", "Regulacja luzów zaworowych", "Hamulce motocyklowe", "Wymiana klocków hamulcowych", "Wymiana płynu hamulcowego", "Wymiana akumulatora", "Diagnostyka motocykla", "Regulacja gaźnika / wtrysku", "Serwis zawieszenia", "Serwis amortyzatorów", "Naprawa elektryki", "Przegląd przed zakupem motocykla", "Przygotowanie do sezonu", "Naprawa po awarii", "Inna usługa"],
    fuelLabel: "Silnik / rodzaj napędu",
    serviceLabel: "Jaka usługa motocyklowa?",
  },
  van: {
    label: "Dostawczy",
    brands: ["Mercedes-Benz Vans", "Volkswagen Commercial Vehicles", "Ford", "Renault", "Peugeot", "Citroen", "Fiat", "Opel", "Iveco", "MAN", "Toyota", "Nissan", "Maxus", "Inna marka"],
    models: {
      "Mercedes-Benz Vans": ["Sprinter", "Vito", "Viano", "Citan", "eCitan", "eSprinter", "eVito", "Klasa V", "T-Class"],
      "Volkswagen Commercial Vehicles": [
        "Caddy",
        "Transporter",
        "Transporter Electric",
        "Caravelle",
        "Multivan",
        "Crafter",
        "Amarok",
        "ID. Buzz Cargo",
      ],
      Ford: [
        "Transit",
        "Transit Custom",
        "Transit Connect",
        "Transit Courier",
        "E-Transit",
        "E-Transit Custom",
        "E-Transit Courier",
        "Ranger",
      ],
      Renault: ["Kangoo", "Trafic", "Trafic E-Tech", "Master", "Master E-Tech", "Express Van"],
      Peugeot: ["Partner", "e-Partner", "Expert", "e-Expert", "Boxer", "e-Boxer", "Rifter"],
      Citroen: ["Berlingo", "ë-Berlingo", "Jumpy", "ë-Jumpy", "Jumper", "ë-Jumper", "SpaceTourer"],
      Fiat: ["Doblo", "Scudo", "Scudo Electric", "Talento", "Ducato", "E-Ducato", "Fiorino"],
      Opel: ["Combo", "Vivaro", "Vivaro-e", "Movano", "Movano-e", "Zafira Life"],
      Iveco: ["Daily", "Eurocargo"],
      MAN: ["TGE"],
      Toyota: ["Proace", "Proace City", "Hilux"],
      Nissan: ["NV200", "NV300", "NV400", "Primastar", "Interstar", "Navara", "Townstar Van"],
      Maxus: ["Deliver 3", "Deliver 9", "eDeliver 3", "eDeliver 9"],
      "Inna marka": ["Inny model"],
    },
    fuels: ["Diesel", "Benzyna", "LPG", "Hybryda", "Elektryczny", "Nie wiem"],
    services: ["Wymiana oleju i filtrów", "Diagnostyka komputerowa", "Hamulce", "Zawieszenie", "Sprzęgło", "Rozrząd", "Turbina", "Układ paliwowy", "DPF / EGR", "Akumulator", "Wymiana opon dostawczych", "Geometria kół", "Klimatyzacja", "Przegląd przed trasą", "Naprawa po awarii", "Serwis floty", "Inna usługa"],
    fuelLabel: "Silnik / paliwo",
    serviceLabel: "Jaka usługa dla pojazdu dostawczego?",
  },
};

const PRIORITY_LABELS = ["Wszystkie", "Wpisz ręcznie", "Dowolne", "Inne"] as const;

function getPriorityIndex(value: string) {
  const normalized = value.trim().toLowerCase();
  return PRIORITY_LABELS.findIndex((label) => normalized === label.toLowerCase() || normalized.startsWith(`${label.toLowerCase()} `));
}

export function sortAlphabetically(items: string[]) {
  return [...items].sort((a, b) => {
    const aPriority = getPriorityIndex(a);
    const bPriority = getPriorityIndex(b);
    if (aPriority !== -1 || bPriority !== -1) {
      if (aPriority === -1) return 1;
      if (bPriority === -1) return -1;
      return aPriority - bPriority;
    }
    return a.localeCompare(b, "pl", { sensitivity: "base" });
  });
}

export function sortYearsDesc(years: Array<string | number>) {
  return [...years].sort((a, b) => Number(b) - Number(a));
}

export function getVehicleTypeLabel(vehicleType: string) {
  return vehicleTypeOptions.find((item) => item.key === vehicleType)?.label ?? vehicleType;
}

const INNA_MARKA = "Inna marka";
const INNY_MODEL = "Inny model";

export function getVehicleBrands(vehicleType: string) {
  const brands = vehicleData[vehicleType as VehicleTypeKey]?.brands ?? [];
  const rest = brands.filter((b) => b !== INNA_MARKA);
  return [...sortAlphabetically(rest), ...(brands.includes(INNA_MARKA) ? [INNA_MARKA] : [])];
}

export function getVehicleModels(vehicleType: string, brand: string) {
  const raw = vehicleData[vehicleType as VehicleTypeKey]?.models[brand] ?? [];
  const withoutInny = raw.filter((m) => m !== INNY_MODEL);
  return [...sortAlphabetically(withoutInny), INNY_MODEL];
}

export function getVehicleFuels(vehicleType: string) {
  return sortAlphabetically(vehicleData[vehicleType as VehicleTypeKey]?.fuels ?? []);
}

export function getVehicleServices(vehicleType: string) {
  return sortAlphabetically(vehicleData[vehicleType as VehicleTypeKey]?.services ?? []);
}

export function getAllServiceOptions() {
  const allServices = Object.values(vehicleData).flatMap((config) => config.services);
  return sortAlphabetically(Array.from(new Set(allServices)));
}

export function getVehicleYears(maxYear = new Date().getFullYear() + 1, minYear = 1955) {
  return sortYearsDesc(Array.from({ length: maxYear - minYear + 1 }, (_, i) => String(minYear + i))).map(String);
}
